###
GET http://localhost:8080/owner/all

###
GET http://localhost:8080/owner/1

###
POST http://localhost:8080/owner/1/update/address
Content-Type: application/text

3a, Horizon Road, Vile Village, TT12 6PD

###
POST http://localhost:8080/owner/1/update/address
Content-Type: application/text

26, The Avenue, Orchard on Sea, BB4 3XT

###
GET http://localhost:8080/pet/2

###
POST http://localhost:8080/pet/add
Content-Type: application/json

{
  "id": 0,
  "name": "Snuffler",
  "dateOfBirth": "2022-10-03",
  "owner": {
    "id": 1,
    "address": "",
    "email": "",
    "name": "",
    "telephone": "",
    "pets": null
  },
  "typeOfAnimal": "Dog"
}

###
POST http://localhost:8080/owner/create
Content-Type: application/json

{
  "address": "43, High Road, Meadow-under-Hill, F12 6GX",
  "email": "po4@tt.com",
  "name": "Pet owner 4",
  "telephone": "+44 2222 444444",
  "password": "pet_owner_4"
}

###
POST http://localhost:8080/owner/create
Content-Type: application/json

{
  "address": "3a, Horizon Road, Vile Village, TT12 6PD",
  "email": "po5@tt.com",
  "name": "Pet owner 5",
  "telephone": "+44 3333 555555",
  "password": "pet_owner_5"
}

###
DELETE http://localhost:8080/owner/4

###
DELETE http://localhost:8080/owner/3

###
POST http://localhost:8080/owner/checkCredentials
Content-Type: application/json

{
  "email" : "po3@po.com",
  "password" : "pet_owner_3"
}

###
POST http://localhost:8080/owner/checkCredentials
Content-Type: application/json

{
  "email" : "po3@po.com",
  "password" : "wrong_password"
}

###
POST http://localhost:8080/owner/checkCredentials
Content-Type: application/json

{
  "email" : "wrong_email@po.com",
  "password" : "pet_owner_3"
}
